theme: minima
title: Hong An
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: Hong_An_
    github: anhong11
header_pages:
  - Research.md
  - Publications.md
  - About.md
plugins:
 - jekyll-feed
 - jekyll-seo-tag
