name: "Hong An"
output_dir: "."
exclude: ["README.md", "LICENSE.md"]
navbar:
  title: Hong An
  left:
  - text: Research
    icon: fa-laptop
    href: research.html
  - text: Publications
    icon: fa-newspaper-o
    href: publications.html
 
  right:
  - icon: fa-github-square fa-lg
    href: https://github.com/pblischak
  - icon: fa-linkedin fa-lg
    href: https://linkedin.com/in/paulblischak
  - icon: fa-twitter-square fa-lg
    href: https://twitter.com/PaulBlischak
output:
  html_document:
    theme: flatly
    highlight: textmate
    include:
      after_body: footer.md
    lib_dir: site_libs
    self_contained: no

theme: jekyll-theme-slate